# Generated by Django 5.2.12 on 2026-06-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_interviewschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drive',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
